<?xml version="1.0"?>
<doc>
    <assembly>
        <name>KeLi.Common.Revit</name>
    </assembly>
    <members>
        <member name="T:KeLi.Common.Revit.Builder.BaseBuilder">
            <summary>
            Base builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddLevel(Autodesk.Revit.DB.Document,System.Double)">
            <summary>
                 new level.
            </summary>
            <param name="doc"></param>
            <param name="elevation"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddWall(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Autodesk.Revit.DB.Curve})">
            <summary>
            Adds the new wall.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddWall(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.ElementId)">
            <summary>
            Adds the new wall.
            </summary>
            <param name="doc"></param>
            <param name="curve"></param>
            <param name="lvlId"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddWall(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Autodesk.Revit.DB.Curve},Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId)">
            <summary>
            Adds the new wall.
            </summary>
            <param name="doc"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="profile"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddWall(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Autodesk.Revit.DB.Curve},Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ)">
            <summary>
            Adds the new wall.
            </summary>
            <param name="doc"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="profile"></param>
            <param name="normal"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddFloor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArray)">
            <summary>
            Adds the new floor.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddFloor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.FloorType,Autodesk.Revit.DB.Level)">
            <summary>
            Adds the new floor.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <param name="type"></param>
            <param name="lvl"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddFloor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.FloorType,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.XYZ)">
            <summary>
            Adds the new floor.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <param name="type"></param>
            <param name="lvl"></param>
            <param name="normal"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddExtrusionRoof(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.ReferencePlane,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.RoofType,System.Double,System.Double)">
            <summary>
            Adds the new extrusion roof.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <param name="plane"></param>
            <param name="lvl"></param>
            <param name="type"></param>
            <param name="start"></param>
            <param name="end"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.BaseBuilder.AddFootPrintRoof(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.RoofType,Autodesk.Revit.DB.ModelCurveArray@)">
            <summary>
            Adds the new foot print roof.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <param name="lvl"></param>
            <param name="type"></param>
            <param name="model"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.FamilyInstanceBuilder">
            <summary>
            Family instance builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilyInstance(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">
            <summary>
            Adds the new family instance.
            </summary>
            <param name="doc"></param>
            <param name="location"></param>
            <param name="symbol"></param>
            <param name="lvl"></param>
            <param name="type"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilyInstance(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.StructuralType)">
            <summary>
            Adds the new family instance.
            </summary>
            <param name="doc"></param>
            <param name="location"></param>
            <param name="symbol"></param>
            <param name="elm"></param>
            <param name="type"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilyInstance(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">
            <summary>
            Adds the new family instance.
            </summary>
            <param name="doc"></param>
            <param name="location"></param>
            <param name="symbol"></param>
            <param name="elm"></param>
            <param name="lvl"></param>
            <param name="type"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilyInstance(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.StructuralType)">
            <summary>
            Adds the new family instance.
            </summary>
            <param name="doc"></param>
            <param name="location"></param>
            <param name="symbol"></param>
            <param name="elm"></param>
            <param name="type"></param>
            <param name="direction"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilySymbol(Autodesk.Revit.UI.UIApplication,System.String,Autodesk.Revit.DB.CurveArrArray,Autodesk.Revit.DB.SketchPlane,System.Double)">
            <summary>
            Adds the new family symbol.
            </summary>
            <param name="uiapp"></param>
            <param name="rfa"></param>
            <param name="profile"></param>
            <param name="plane"></param>
            <param name="end"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilySymbol(Autodesk.Revit.UI.UIApplication,System.String,Autodesk.Revit.DB.SweepProfile,Autodesk.Revit.DB.ReferenceArray,System.Int32)">
            <summary>
            Adds the new family symbol.
            </summary>
            <param name="uiapp"></param>
            <param name="rfa"></param>
            <param name="profile"></param>
            <param name="path"></param>
            <param name="index"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilySymbol(Autodesk.Revit.UI.UIApplication,System.String)">
            <summary>
            Adds the new family symbol.
            </summary>
            <param name="uiapp"></param>
            <param name="rfa"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.FamilyInstanceBuilder.AddFamilySymbol(Autodesk.Revit.UI.UIApplication,System.String,System.Action{Autodesk.Revit.DB.Document})">
            <summary>
            Adds the new family symbol.
            </summary>
            <param name="uiapp"></param>
            <param name="rft"></param>
            <param name="act"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.GroupBuilder">
            <summary>
            Group builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.GroupBuilder.AddGroup(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Autodesk.Revit.DB.ElementId})">
            <summary>
            Adds the new group.
            </summary>
            <param name="doc"></param>
            <param name="elmIds"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.MaterialBuilder">
            <summary>
            Material builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.MaterialBuilder.AddMaterial(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Adds the new material.
            </summary>
            <param name="doc"></param>
            <param name="name"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.PipeBuilder">
            <summary>
            Pipe builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PipeBuilder.AddPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">
            <summary>
            Adds the new pipe.
            </summary>
            <param name="doc"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="start"></param>
            <param name="end"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PipeBuilder.AddPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.XYZ)">
            <summary>
            Adds the new pipe.
            </summary>
            <param name="doc"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="start"></param>
            <param name="end"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PipeBuilder.AddPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
            <summary>
            Adds the new pipe.
            </summary>
            <param name="doc"></param>
            <param name="systemId"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="start"></param>
            <param name="end"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PipeBuilder.AddFlexPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,System.Collections.Generic.List{Autodesk.Revit.DB.XYZ})">
            <summary>
            Adds the new flex pipe.
            </summary>
            <param name="doc"></param>
            <param name="systemId"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="points"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PipeBuilder.AddFlexPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Collections.Generic.List{Autodesk.Revit.DB.XYZ})">
            <summary>
            Adds the new flex pipe.
            </summary>
            <param name="doc"></param>
            <param name="systemId"></param>
            <param name="typeId"></param>
            <param name="lvlId"></param>
            <param name="end"></param>
            <param name="points"></param>
            <param name="start"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PipeBuilder.AddConduit(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.ElementId)">
            <summary>
            Adds the new conduit.
            </summary>
            <param name="doc"></param>
            <param name="typeId"></param>
            <param name="start"></param>
            <param name="end"></param>
            <param name="lvlId"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.PlaneBuilder">
            <summary>
            Plane builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PlaneBuilder.AddReferencePlane(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.View)">
            <summary>
            Adds the new reference plane.
            </summary>
            <param name="doc"></param>
            <param name="bubble"></param>
            <param name="free"></param>
            <param name="vector"></param>
            <param name="view"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PlaneBuilder.AddSketchPlane(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)">
            <summary>
            Adds the new sketch plane.
            </summary>
            <param name="doc"></param>
            <param name="datumId"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PlaneBuilder.AddSketchPlane(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Plane)">
            <summary>
            Adds the new sketch plane.
            </summary>
            <param name="doc"></param>
            <param name="plane"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.PlaneBuilder.AddSketchPlane(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Reference)">
            <summary>
            Adds the new sketch plane.
            </summary>
            <param name="doc"></param>
            <param name="refer"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.SweepBuilder">
            <summary>
            Sweep builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.SweepBuilder.AddSweep(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.SweepProfile,Autodesk.Revit.DB.ReferenceArray,System.Int32)">
            <summary>
            Adds the new sweep.
            </summary>
            <param name="doc"></param>
            <param name="path"></param>
            <param name="profile"></param>
            <param name="index"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.SweepBuilder.AddExtrusion(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArrArray,Autodesk.Revit.DB.SketchPlane,System.Double)">
            <summary>
            Adds the new extrusion.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <param name="plane"></param>
            <param name="end"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.SweepBuilder.AddProfile(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.CurveArrArray)">
            <summary>
            Adds the new profile.
            </summary>
            <param name="doc"></param>
            <param name="profile"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Builder.ViewBuilder">
            <summary>
            View builder.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Builder.ViewBuilder.AddViewSection(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Adds the new view section.
            </summary>
            <param name="doc"></param>
            <param name="elmId"></param>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Properties.Resources">
            <summary>
              A strongly-typed resource class, for looking up localized strings, etc.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Properties.Resources.ResourceManager">
            <summary>
              Returns the cached ResourceManager instance used by this class.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Properties.Resources.Culture">
            <summary>
              Overrides the current thread's CurrentUICulture property for all
              resource lookups using this strongly typed resource class.
            </summary>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.GeometryPosition">
            <summary>
            Geometry relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Inner">
            <summary>
            Returns inner relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Overlay">
            <summary>
            Returns overlay relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Cross">
            <summary>
            Returns cross relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Edge">
            <summary>
            Returns edge relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Parallel">
            <summary>
            Returns parallel relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Vertical">
            <summary>
            Returns vertical relationship.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Relation.GeometryPosition.Other">
            <summary>
            Returns other relationship.
            </summary>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.PointRelation">
            <summary>
            About two points relationship.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointRelation.GetPlanePosition(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the point pt1 and the point pt2 about plane direction relationship.
            </summary>
            <param name="pt1"></param>
            <param name="pt2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointRelation.GetSpacePosition(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the point pt1 and the point pt2 about space direction relationship.
            </summary>
            <param name="pt1"></param>
            <param name="pt2"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.LinePlaneRelation">
            <summary>
            About a line and a plane relationship.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LinePlaneRelation.GetPlanePosition(Autodesk.Revit.DB.Line,System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the line and the plane about plane direction relationship.
            </summary>
            <param name="line"></param>
            <param name="plane"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LinePlaneRelation.GetSpacePosition(Autodesk.Revit.DB.Line,System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the line and the plane about space direction relationship.
            </summary>
            <param name="line"></param>
            <param name="plane"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.LineRelation">
            <summary>
            About two lines relationship.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetPlanePosition(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.XYZ@,System.Boolean)">
            <summary>
            Gets the line line1 and the line line2 about plane direction relationship.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <param name="insPt"></param>
            <param name="isTouch"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetSpacePosition(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.XYZ@,System.Boolean)">
            <summary>
            Gets the line line1 and the line line2 about space direction relationship.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <param name="insPt"></param>
            <param name="isTouch"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.IsSpaceVertical(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the result of whether the line line1 and the line line2 is space vertical.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.IsSpaceParallel(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the result of whether the line line1 and the line line2 is space parallel.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.ToPlaneLine(Autodesk.Revit.DB.Line)">
            <summary>
            Converts to plane line.
            </summary>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.IsPlaneParallel(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the result of whether the line line1 and the line line2 is plane parallel.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.IsPlaneVertical(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the result of whether the line line1 and the line line2 is plane vertical.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetPlaneInsPoint(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line,System.Boolean)">
            <summary>
            Gets the intersection of the line line1 and the line line2 on plane.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <param name="isTouch"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetPlaneInsPointList(Autodesk.Revit.DB.Line,System.Collections.Generic.List{Autodesk.Revit.DB.Line},System.Boolean)">
            <summary>
            Gets the intersections of the line and the lines on plane.
            </summary>
            <param name="line"></param>
            <param name="lines"></param>
            <param name="isTouch"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetSpaceInsPoint(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line,System.Boolean)">
            <summary>
            Gets the intersection of the line line1 and the line line2 on space.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <param name="isTouch"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetSpaceInsPointList(Autodesk.Revit.DB.Line,System.Collections.Generic.List{Autodesk.Revit.DB.Line},System.Boolean)">
            <summary>
            Gets the intersections of the line and the lines on space.
            </summary>
            <param name="line"></param>
            <param name="lines"></param>
            <param name="isTouch"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetDistinctPointList(System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the distinct vectors of the lines.
            </summary>
            <param name="lines"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetBoundaryPointList(System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets points of the boundary.
            </summary>
            <param name="lines"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetMaxPoint(Autodesk.Revit.DB.Line)">
            <summary>
            Gets the max point of the line.
            </summary>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetMaxPoint(System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the min point of the lines.
            </summary>
            <param name="lines"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetMinPoint(Autodesk.Revit.DB.Line)">
            <summary>
            Gets the min point of the line.
            </summary>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetMinPoint(System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the min point of the lines.
            </summary>
            <param name="lines"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetMidPoint(Autodesk.Revit.DB.Line)">
            <summary>
            Gets the middle point of the line.
            </summary>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineRelation.GetMidPoint(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the middle point of the two lines in nearest area.
            </summary>
            <param name="line1"></param>
            <param name="line2"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.LineSolidRelation">
            <summary>
            About a line and a solid relationship
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.LineSolidRelation.GetPosition(Autodesk.Revit.DB.Line,System.Collections.Generic.List{System.Collections.Generic.List{Autodesk.Revit.DB.Line}})">
            <summary>
            Gets the line and the solid relationship.
            </summary>
            <param name="line"></param>
            <param name="solid"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.PlaneRelation">
            <summary>
            About two plane relationship
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PlaneRelation.GetPlanePosition(System.Collections.Generic.List{Autodesk.Revit.DB.Line},System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the plane plane1 and the plane plane2 about plane direction relationship.
            </summary>
            <param name="plane1"></param>
            <param name="plane2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PlaneRelation.GetSpacePosition(System.Collections.Generic.List{Autodesk.Revit.DB.Line},System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the plane plane1 and the plane plane2 about space direction relationship.
            </summary>
            <param name="plane1"></param>
            <param name="plane2"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.PlaneSolidRelation">
            <summary>
            About a plane and a solid relationship
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PlaneSolidRelation.GetPosition(System.Collections.Generic.List{Autodesk.Revit.DB.Line},System.Collections.Generic.List{System.Collections.Generic.List{Autodesk.Revit.DB.Line}})">
            <summary>
            Gets the plane and the solid relationship.
            </summary>
            <param name="plane"></param>
            <param name="solid"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.PointLineRelation">
            <summary>
            About a point and a line relationship
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointLineRelation.GetPlanePosition(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the point and the line about plane direction relationship.
            </summary>
            <param name="pt"></param>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointLineRelation.GetSpacePosition(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Line)">
            <summary>
            Gets the point and the line about space direction relationship.
            </summary>
            <param name="pt"></param>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointLineRelation.GetMaxPoint(System.Collections.Generic.List{Autodesk.Revit.DB.XYZ})">
            <summary>
            Gets the max point of some points that x, y, z is max value.
            </summary>
            <param name="pts"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointLineRelation.GetMinPoint(System.Collections.Generic.List{Autodesk.Revit.DB.XYZ})">
            <summary>
            Gets the min point of some points that x, y, z is min value.
            </summary>
            <param name="pts"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.PointPlaneRelation">
            <summary>
            About a point and a plane relationship
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointPlaneRelation.GetPlanePosition(Autodesk.Revit.DB.XYZ,Autodesk.Revit.UI.Selection.PickedBox)">
            <summary>
            Gets the point and the plane about plane direction relationship.
            </summary>
            <param name="pt"></param>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointPlaneRelation.GetSpacePosition(Autodesk.Revit.DB.XYZ,Autodesk.Revit.UI.Selection.PickedBox)">
            <summary>
            Gets the point and the plane about space direction relationship.
            </summary>
            <param name="pt"></param>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointPlaneRelation.InPlanePolygon(Autodesk.Revit.DB.XYZ,System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the result of whether the point is in the plane direction polygon.
            </summary>
            <param name="pt"></param>
            <param name="lines"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointPlaneRelation.InSpacePolygon(Autodesk.Revit.DB.XYZ,System.Collections.Generic.List{Autodesk.Revit.DB.Line})">
            <summary>
            Gets the result of whether the point is in the space direction polygon.
            </summary>
            <param name="pt"></param>
            <param name="lines"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.PointSolidRelation">
            <summary>
            About a point and a solid relationship
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.PointSolidRelation.GetPosition(Autodesk.Revit.DB.XYZ,System.Collections.Generic.List{System.Collections.Generic.List{Autodesk.Revit.DB.Line}})">
            <summary>
            Gets the point and the solid relationship
            </summary>
            <param name="pt"></param>
            <param name="solid"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Relation.SolidRelaction">
            <summary>
            About a solid and a solid relationship.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.RejectPlaneBox(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element)">
            <summary>
            Gets the result of fast plane rejection of the box.
            </summary>
            <param name="doc"></param>
            <param name="elm1"></param>
            <param name="elm2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.RejectPlaneBox(Autodesk.Revit.DB.BoundingBoxXYZ,Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the result of fast plane rejection of the box.
            </summary>
            <param name="box1"></param>
            <param name="box2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.RejectSpaceBox(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element)">
            <summary>
            Gets the result of fast space rejection of the box.
            </summary>
            <param name="doc"></param>
            <param name="elm1"></param>
            <param name="elm2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.RejectSpaceBox(Autodesk.Revit.DB.BoundingBoxXYZ,Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the result of fast space rejection of the box.
            </summary>
            <param name="box1"></param>
            <param name="box2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossPlaneBox(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element)">
            <summary>
            Gets the result of plane cross of the box.
            </summary>
            <param name="doc"></param>
            <param name="elm1"></param>
            <param name="elm2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossPlaneBox(Autodesk.Revit.DB.BoundingBoxXYZ,Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the result of plane cross of the box.
            </summary>
            <param name="box1"></param>
            <param name="box2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossSpaceBox(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element)">
            <summary>
            Gets the result of space cross of the box.
            </summary>
            <param name="doc"></param>
            <param name="elm1"></param>
            <param name="elm2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossSpaceBox(Autodesk.Revit.DB.BoundingBoxXYZ,Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
             Gets the result of space cross of the box.
            </summary>
            <param name="box1"></param>
            <param name="box2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CutElement(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.CutFailureReason)">
            <summary>
            Gets the result of between the two elements can cut.
            </summary>
            <param name="elm1"></param>
            <param name="elm2"></param>
            <param name="reason"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossGeometry(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element)">
            <summary>
            Gets the result of between the two elements cross.
            </summary>
            <param name="elm1"></param>
            <param name="elm2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossGeometry(Autodesk.Revit.DB.GeometryElement,Autodesk.Revit.DB.GeometryElement)">
            <summary>
            Gets the result of between valid geometry of the two elements cross.
            </summary>
            <param name="ge1"></param>
            <param name="ge2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossSolid(System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.Solid},System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.Solid})">
            <summary>
            Gets the result of between some solids and others cross.
            </summary>
            <param name="solid1s"></param>
            <param name="solid2s"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossSolid(Autodesk.Revit.DB.Solid,System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.Solid})">
            <summary>
            Gets the result of between a solid and some solids cross.
            </summary>
            <param name="solid"></param>
            <param name="solids"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Relation.SolidRelaction.CrossSolid(Autodesk.Revit.DB.Solid,Autodesk.Revit.DB.Solid)">
            <summary>
            Gets the result of between a solid and a solid cross.
            </summary>
            <param name="solid1"></param>
            <param name="solid2"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.ButtonInfo`1">
            <summary>
            Button info.
            </summary>
            <typeparam name="T"></typeparam>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ButtonInfo`1.#ctor(System.String)">
            <summary>
            Button info.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ButtonInfo`1.CreatePbd">
            <summary>
            Creates the button.
            </summary>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.CalcType">
            <summary>
            Calc type.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.CalcType.FaceNum">
            <summary>
            Base face to calc.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.CalcType.FacePointNum">
            <summary>
            Base point on face to calc.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.CalcType.SolidPointNum">
            <summary>
            Base point on solid to calc.
            </summary>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.ConnectorUtil">
            <summary>
            Connection utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.ConnectWall(Autodesk.Revit.DB.Document)">
            <summary>
            Connects the wall.
            </summary>
            <param name="doc"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.ConnectInstance(Autodesk.Revit.DB.Document)">
            <summary>
            Connects the family instances.
            </summary>
            <param name="doc"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.ConnectPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.MEPCurve)">
            <summary>
            Connects the two pipes.
            </summary>
            <param name="doc"></param>
            <param name="pipe1"></param>
            <param name="pipe2"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.ConnectPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.MEPCurve)">
            <summary>
            Connects the three pipes.
            </summary>
            <param name="doc"></param>
            <param name="pipe1"></param>
            <param name="pipe2"></param>
            <param name="pipe3"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.ConnectPipe(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.MEPCurve)">
            <summary>
            Connects the four pipes.
            </summary>
            <param name="doc"></param>
            <param name="pipe1"></param>
            <param name="pipe2"></param>
            <param name="pipe3"></param>
            <param name="pipe4"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.GetLatestConnector(Autodesk.Revit.DB.MEPCurve,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the element's the latest connector.
            </summary>
            <param name="pipe"></param>
            <param name="point"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.GetLatestConnector(Autodesk.Revit.DB.ConnectorSet,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the element's the latest connector.
            </summary>
            <param name="connectors"></param>
            <param name="point"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.JoinElmBySameFloor``1(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.Linq.IGrouping{Autodesk.Revit.DB.ElementId,``0}})">
            <summary>
             To connect elements on same floor.
            </summary>
            <param name="doc"></param>
            <param name="wallGroups"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.JoinElmByAdjacentFloor``1(Autodesk.Revit.DB.Document,System.Collections.Generic.IReadOnlyList{System.Linq.IGrouping{Autodesk.Revit.DB.ElementId,``0}})">
            <summary>
            To connect elements on adjacent floor.
            </summary>
            <param name="doc"></param>
            <param name="wallGroups"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.JoinElmBySameFloor``1(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.Linq.IGrouping{System.Double,``0}})">
            <summary>
             To connect elements on same floor.
            </summary>
            <param name="doc"></param>
            <param name="wallGroups"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ConnectorUtil.JoinElmByAdjacentFloor``1(Autodesk.Revit.DB.Document,System.Collections.Generic.IReadOnlyList{System.Linq.IGrouping{System.Double,``0}})">
            <summary>
            To connect elements on adjacent floor.
            </summary>
            <param name="doc"></param>
            <param name="wallGroups"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.KeyCodeEnum">
            <summary>
            Key code enum.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.KeyCodeEnum.LeftShift">
            <summary>
            Left shift key code.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.KeyCodeEnum.RightShift">
            <summary>
            Right shift key code.
            </summary>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.MeshUtil">
            <summary>
            Mesh utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetDispersedLines(Autodesk.Revit.DB.Curve,System.Int32)">
            <summary>
            Gets the dispersed line set.
            </summary>
            <param name="curve"></param>
            <param name="gapNum"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetDispersedLines(System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},System.Int32)">
            <summary>
            Gets the dispersed line set.
            </summary>
            <param name="points"></param>
            <param name="gapNum"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetMeshTriangles(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's triange set.
            </summary>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetMeshTriangles(Autodesk.Revit.DB.Mesh)">
            <summary>
            Gets the element's triange set.
            </summary>
            <param name="mesh"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetMeshes(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's mesh set.
            </summary>
            <param name="elm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetFaces(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's face set.
            </summary>
            <param name="elm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetFacePoints(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's point set on face.
            </summary>
            <param name="elm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetSolidPoints(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's point set base on distance.
            </summary>
            <param name="elm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetEdges(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's edge set.
            </summary>
            <param name="elm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetValidSolids(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's valid solid set.
            </summary>
            <param name="elm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.MeshUtil.GetValidSolids(Autodesk.Revit.DB.GeometryElement,System.Int32)">
            <summary>
            Gets the element's valid solid set.
            </summary>
            <param name="ge"></param>
            <param name="precision"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.FilterAssist">
            <summary>
            Filter Assist.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.FilterAssist.Checkout(Autodesk.Revit.DB.Document,System.Boolean)">
            <summary>
            Checkouts all elements in the document.
            </summary>
            <param name="doc"></param>
            <param name="onlyCurrentView"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.FilterAssist.GetTypeElements``1(Autodesk.Revit.DB.Document,System.Boolean)">
            <summary>
            Gets the specified type of the element set.
            </summary>
            <param name="doc"></param>
            <param name="onlyCurrentView"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.FilterAssist.GetCategoryElements(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.BuiltInCategory,System.Boolean)">
            <summary>
            Gets the specified category of the element set.
            </summary>
            <param name="doc"></param>
            <param name="category"></param>
            <param name="onlyCurrentView"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.FilterAssist.GetTypeElements``1(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.BuiltInCategory,System.Boolean)">
            <summary>
            Gets the specified type and category of the element set.
            </summary>
            <param name="doc"></param>
            <param name="category"></param>
            <param name="onlyCurrentView"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.FilterAssist.GetElements(Autodesk.Revit.DB.Document,KeLi.Common.Revit.Widget.CalcType,System.Int32,System.Boolean,System.Boolean)">
            <summary>
            Gets the element set that filter the max number of points.
            </summary>
            <param name="doc"></param>
            <param name="maxNum"></param>
            <param name="moreThan"></param>
            <param name="type"></param>
            <param name="onlyCurrentView"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.FilterAssist.GetMaxElement(Autodesk.Revit.DB.Document,KeLi.Common.Revit.Widget.CalcType,System.Boolean)">
            <summary>
            Gets the max number of points element and the number.
            </summary>
            <param name="doc"></param>
            <param name="type"></param>
            <param name="onlyCurrentView"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.HookHandler">
            <summary>
            Hook handler
            </summary>
            <param name="nCode"></param>
            <param name="wParam"></param>
            <param name="lParam"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.HookUtil">
            <summary>
            Hook utility.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.HookId">
            <summary>
            The hook id.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.WhKeyboardLl">
            <summary>
            The key board message.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.WmKeydown">
            <summary>
            The key down message.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.WmSyskeydown">
            <summary>
            The system key down message.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.WmKeyup">
            <summary>
            The key up message.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.WmSyskeyup">
            <summary>
            The system key up message.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.Handler">
            <summary>
            The hook handler.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.KeyDownEvent">
            <summary>
            The key down event.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.KeyUpEvent">
            <summary>
            The key up event.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.HookUtil.KeyCode">
            <summary>
            The key code.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.Hook(System.Action{System.Int32},System.Action{System.Int32})">
            <summary>
            Starts hook the program.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.Unhook">
            <summary>
            Stops hook the program.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.Callback(System.Int32,System.IntPtr,System.Int32@)">
            <summary>
            Returns callback method result.
            </summary>
            <param name="nCode"></param>
            <param name="wParam"></param>
            <param name="lParam"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.SetWindowsHookEx(System.Int32,KeLi.Common.Revit.Widget.HookHandler,System.IntPtr,System.UInt32)">
            <summary>
            Installs the hook.
            </summary>
            <param name="idHook"></param>
            <param name="lpfn"></param>
            <param name="hMod"></param>
            <param name="dwThreadId"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.UnhookWindowsHookEx(System.IntPtr)">
            <summary>
            Uninstall the hook.
            </summary>
            <param name="hhk"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.CallNextHookEx(System.IntPtr,System.Int32,System.IntPtr,System.Int32@)">
            <summary>
            Gets the next hook.
            </summary>
            <param name="hhk"></param>
            <param name="nCode"></param>
            <param name="wParam"></param>
            <param name="lParam"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.HookUtil.GetModuleHandle(System.String)">
            <summary>
            Gets the module handle.
            </summary>
            <param name="lpModuleName"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.LinkUtil">
            <summary>
            Link utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.OpenCentralFile(Autodesk.Revit.ApplicationServices.Application,System.String,System.String)">
            <summary>
            Opens the central file.
            </summary>
            <param name="app"></param>
            <param name="serverPath"></param>
            <param name="localPath"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.CompactCentralFile(Autodesk.Revit.ApplicationServices.Application,System.String)">
            <summary>
            Compacts the central file.
            </summary>
            <param name="app"></param>
            <param name="centralPath"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SetCentralFile(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Sets the central file.
            </summary>
            <param name="doc"></param>
            <param name="centralPath"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SyncCentralFile(Autodesk.Revit.UI.UIApplication,System.String)">
            <summary>
            syncs the central file.
            </summary>
            <param name="uiapp"></param>
            <param name="comment"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.DetachedFromCentralFile(Autodesk.Revit.ApplicationServices.Application,System.String)">
            <summary>
            detachs from the central file.
            </summary>
            <param name="app"></param>
            <param name="centralPath"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.AddWorkset(Autodesk.Revit.DB.Document,System.String,System.String)">
            <summary>
            Adds the workset.
            </summary>
            <param name="doc"></param>
            <param name="gridLvl"></param>
            <param name="worksetName"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.AddCadLink(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Adds the cad link.
            </summary>
            <param name="doc"></param>
            <param name="linkPath"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.AddCadLinks(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Adds the cad link set.
            </summary>
            <param name="doc"></param>
            <param name="linkPaths"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.AddRevitLink(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Adds the revit link.
            </summary>
            <param name="doc"></param>
            <param name="linkPath"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.AddRevitLinks(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Adds the revit link set.
            </summary>
            <param name="doc"></param>
            <param name="linkPaths"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.RemoveRevitLink(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Deletes the revit link.
            </summary>
            <param name="doc"></param>
            <param name="linkPath"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.RemoveRevitLinks(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Deletes the revit link set.
            </summary>
            <param name="doc"></param>
            <param name="linkPaths"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SetRevitLinks(System.String,System.Collections.Generic.List{System.String})">
            <summary>
            Sets the revit link set.
            </summary>
            <param name="centralPath"></param>
            <param name="linkPaths"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SetRevitLinks(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Sets the revit link set.
            </summary>
            <param name="doc"></param>
            <param name="filePaths"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SetRevitLink(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Sets the revit link.
            </summary>
            <param name="doc"></param>
            <param name="filePath"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.GetRevitLinks(Autodesk.Revit.DB.Document)">
            <summary>
            Gets model's link set.
            </summary>
            <param name="doc"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SaveRevit(Autodesk.Revit.UI.UIApplication,System.String)">
            <summary>
            Saves front model by front end.
            </summary>
            <param name="uiapp"></param>
            <param name="blankPath"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.LinkUtil.SaveRevit(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Saves model by back end.
            </summary>
            <param name="doc"></param>
            <param name="centralPath"></param>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.ParamUtil">
            <summary>
            Parameter utility
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.SetValue(Autodesk.Revit.DB.Element,System.String,System.String)">
            <summary>
            Sets the value of the element's parameter.
            </summary>
            <param name="elm"></param>
            <param name="paramName"></param>
            <param name="value"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.GetValue(Autodesk.Revit.DB.Element,System.String)">
            <summary>
            Gets the value of the element's parameter.
            </summary>
            <param name="elm"></param>
            <param name="paramName"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.GetDefinition(Autodesk.Revit.DB.DefinitionGroup,System.String,System.Boolean)">
            <summary>
            Gets definition by sharing parameter file path.
            </summary>
            <param name="group"></param>
            <param name="paramName"></param>
            <param name="canEdit"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.GetGroup(Autodesk.Revit.DB.DefinitionGroups,System.String)">
            <summary>
            Gets definition groups by sharing parameter file path.
            </summary>
            <param name="groups"></param>
            <param name="groupName"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.GetGroups(Autodesk.Revit.UI.UIApplication,System.String)">
            <summary>
            Gets definition groups by sharing parameter file path.
            </summary>
            <param name="uiapp"></param>
            <param name="paramPath"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.InitParams(Autodesk.Revit.UI.UIApplication,Autodesk.Revit.DB.Element,System.String)">
            <summary>
            Initializes element or type parameter binding.
            </summary>
            <param name="uiapp"></param>
            <param name="elm"></param>
            <param name="paramPath"></param>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.GetGroups(System.String)">
            <summary>
            Getting group list by sharing parameter file path.
            </summary>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.ParamUtil.Group">
            <summary>
            Parameter's group
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.ParamUtil.Group.#ctor(System.String,System.String)">
            <summary>
            Initializing parameter's group.
            </summary>
            <param name="id"></param>
            <param name="groupName"></param>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Group.Id">
            <summary>
            Returns the id of the parameter's group.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Group.GroupName">
            <summary>
            Returns the name of the parameter's group.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Group.Params">
            <summary>
            Returns the parameter list of the parameter's group.
            </summary>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.ParamUtil.Param">
            <summary>
            Element's parameter
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.Guid">
            <summary>
            Returns the guid of the element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.ParamName">
            <summary>
            Returns the name of the element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.DataType">
            <summary>
            Returns the data type of the element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.DataCatetory">
            <summary>
            Returns the data category of the element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.GroupId">
            <summary>
            Returns the group id of the element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.Visible">
            <summary>
            Returns the visible of element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.Description">
            <summary>
            Returns the description of element's parameter.
            </summary>
        </member>
        <member name="P:KeLi.Common.Revit.Widget.ParamUtil.Param.CanEdit">
            <summary>
            Returns the can edit of element's parameter.
            </summary>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.RibbonUtil">
            <summary>
            Custom ribbon utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RibbonUtil.AddButton(Autodesk.Revit.UI.RibbonPanel,Autodesk.Revit.UI.PushButtonData)">
            <summary>
            Adds the button.
            </summary>
            <param name="pnl"></param>
            <param name="pbd"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RibbonUtil.AddButton``1(Autodesk.Revit.UI.RibbonPanel,KeLi.Common.Revit.Widget.ButtonInfo{``0})">
            <summary>
            Adds the button.
            </summary>
            <param name="pnl"></param>
            <param name="info"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RibbonUtil.AddButtons(Autodesk.Revit.UI.RibbonPanel,System.Collections.Generic.List{Autodesk.Revit.UI.PushButtonData})">
            <summary>
            Adds the button set.
            </summary>
            <param name="pnl"></param>
            <param name="pbds"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RibbonUtil.AddPushButton(Autodesk.Revit.UI.RibbonPanel,Autodesk.Revit.UI.PulldownButtonData,System.Collections.Generic.List{Autodesk.Revit.UI.PushButtonData})">
            <summary>
            Adds the push button.
            </summary>
            <param name="pnl"></param>
            <param name="pbd"></param>
            <param name="pbds"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RibbonUtil.AddPushButtons(Autodesk.Revit.UI.RibbonPanel,System.Collections.Generic.Dictionary{Autodesk.Revit.UI.PulldownButtonData,System.Collections.Generic.List{Autodesk.Revit.UI.PushButtonData}})">
            <summary>
            Adds the push button set.
            </summary>
            <param name="pnl"></param>
            <param name="pbds"></param>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.AreaUtil">
            <summary>
            Area utility
            </summary>
            <remarks>
            About implementation:
            First of all, to project the element;
            then, calculate the projection area;
            last, add up to the result variable.
            </remarks>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.AreaUtil.FT2_TO_M2">
            <summary>
            Square foot to spaure meter
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.AreaUtil.GetShadowArea(Autodesk.Revit.DB.Element)">
            <summary>
            Gets the element's projection area.
            </summary>
            <param name="elm">A element</param>
            <remarks>Returns projection area, that area unit is square meter.</remarks>
            <exception cref="T:Autodesk.Revit.Exceptions.ArgumentNullException">The input element is invalid.</exception>
            <returns>Returns projection area.</returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.BoxUtil">
            <summary>
            Box utility
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetBoundingBox(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Document)">
            <summary>
            Gets the bounding box.
            </summary>
            <param name="elm"></param>
            <param name="doc"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetRoundBox(Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the round box.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetRoundBox(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Document)">
            <summary>
            Gets the round box.
            </summary>
            <param name="elm"></param>
            <param name="doc"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetPlaneEdges(Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the plane edge set and z axis value equals no zero.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetPlaneVectors(Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the box's plane 4 vectors.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetSpaceEdges(Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the space edge set.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetSpaceVectors(Autodesk.Revit.DB.BoundingBoxXYZ)">
            <summary>
            Gets the box's space 8 vectors.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetPlaneEdges(Autodesk.Revit.UI.Selection.PickedBox)">
            <summary>
            Gets the plane edge set and z axis value equals no zero.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetPlaneVectors(Autodesk.Revit.UI.Selection.PickedBox)">
            <summary>
            Gets the box's plane 4 vectors.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetSpaceEdges(Autodesk.Revit.UI.Selection.PickedBox)">
            <summary>
            Gets the space edge set.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.BoxUtil.GetSpaceVectors(Autodesk.Revit.UI.Selection.PickedBox)">
            <summary>
            Gets the box's space 8 vectors.
            </summary>
            <param name="box"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.NormalUtil">
            <summary>
            Noramal utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NormalUtil.GetDotProduct(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the dot product.
            </summary>
            <param name="p1"></param>
            <param name="p2"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NormalUtil.GetSpaceNormal(Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the space normal vector.
            </summary>
            <param name="point"></param>
            <param name="curve"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NormalUtil.GetSpaceNormal(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">
            <summary>
            Gets the space normal vector.
            </summary>
            <param name="p1"></param>
            <param name="p2"></param>
            <param name="p3"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.NumberUtil">
            <summary>
            Number utility.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.NumberUtil.MM_TO_INCH">
            <summary>
            Millimeter to inch.
            </summary>
        </member>
        <member name="F:KeLi.Common.Revit.Widget.NumberUtil.MM_TO_FT">
            <summary>
            Millimeter to foot.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NumberUtil.GetRound(System.Double,System.Int32)">
            <summary>
            Gets the round value.
            </summary>
            <param name="num"></param>
            <param name="precision"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NumberUtil.GetPow(System.Double,System.Int32)">
            <summary>
            Gets the distance square.
            </summary>
            <param name="d"></param>
            <param name="pow"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NumberUtil.ToFoot(System.Double)">
            <summary>
            Millimeter to foot.
            </summary>
            <param name="mm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NumberUtil.ToInch(System.Double)">
            <summary>
            Millimeter to inch.
            </summary>
            <param name="mm"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NumberUtil.ToAngle(System.Double)">
            <summary>
            The radian to the angle.
            </summary>
            <param name="radian"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.NumberUtil.ToRadian(System.Double)">
            <summary>
            The angle to the radian.
            </summary>
            <param name="angle"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.RoomSelection">
            <summary>
            Room selection.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RoomSelection.AllowElement(Autodesk.Revit.DB.Element)">
            <summary>
            Allows the element to be picked.
            </summary>
            <param name="elem"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.RoomSelection.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)">
            <summary>
            Allows the element to be referenced.
            </summary>
            <param name="reference"></param>
            <param name="position"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.AutoUtil">
            <summary>
            Auto action utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.AutoUtil.AutoTransaction(Autodesk.Revit.DB.Document,System.Action)">
            <summary>
            To auto execute transaction.
            </summary>
            <param name="doc"></param>
            <param name="act"></param>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.TypeConverter">
            <summary>
            Type converter.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.TypeConverter.ToPlaneLine(Autodesk.Revit.DB.Curve)">
            <summary>
            Convers the space curve to the plane line.
            </summary>
            <param name="line"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.TypeConverter.ToPlanePoint(Autodesk.Revit.DB.XYZ)">
            <summary>
            Convers the space point to the plane point.
            </summary>
            <param name="point"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.TypeConverter.ToReferArray(System.Collections.Generic.List{Autodesk.Revit.DB.Reference})">
            <summary>
            Converts the reference set to the reference array.
            </summary>
            <param name="refers"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.TypeConverter.ToCurveArrArray(System.Collections.Generic.List{Autodesk.Revit.DB.CurveArray})">
            <summary>
            Converts the curve array set to the curve arr array.
            </summary>
            <param name="curvess"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.TypeConverter.ToCurveArray(System.Collections.Generic.List{Autodesk.Revit.DB.Curve})">
            <summary>
            Converts the curve set to the curve array.
            </summary>
            <param name="curves"></param>
            <returns></returns>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.TypeConverter.GetRoundPoint(Autodesk.Revit.DB.XYZ,System.Int32)">
            <summary>
            Gets the round point with custom precision.
            </summary>
            <param name="point"></param>
            <param name="precision"></param>
            <returns></returns>
        </member>
        <member name="T:KeLi.Common.Revit.Widget.VisabilityUtil">
            <summary>
            Visability utility.
            </summary>
        </member>
        <member name="M:KeLi.Common.Revit.Widget.VisabilityUtil.SetExtrusionVisible(Autodesk.Revit.DB.GenericForm)">
            <summary>
            Sets the element's visible.
            </summary>
            <param name="gf"></param>
        </member>
    </members>
</doc>
